//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fetch(&quot;[balance_url]&quot;, {
        ///  &quot;headers&quot;: {
        ///    &quot;accept&quot;: &quot;application/json, text/plain, */*&quot;,
        ///    &quot;accept-language&quot;: &quot;en-US,en;q=0.9,ko;q=0.8&quot;,
        ///    &quot;cache-control&quot;: &quot;no-cache&quot;,
        ///    &quot;pragma&quot;: &quot;no-cache&quot;,
        ///    &quot;priority&quot;: &quot;u=1, i&quot;,
        ///    &quot;sec-ch-ua&quot;: &quot;\&quot;Chromium\&quot;;v=\&quot;124\&quot;, \&quot;Google Chrome\&quot;;v=\&quot;124\&quot;, \&quot;Not-A.Brand\&quot;;v=\&quot;99\&quot;&quot;,
        ///    &quot;sec-ch-ua-mobile&quot;: &quot;?0&quot;,
        ///    &quot;sec-ch-ua-platform&quot;: &quot;\&quot;Windows\&quot;&quot;,
        ///    &quot;sec-fetch-dest&quot;: &quot;empty&quot;,
        ///    &quot;sec-fetch-mode&quot;: &quot;cors&quot;,
        ///    &quot;sec-fetch-site&quot;: &quot;same-origin&quot;,
        ///    &quot;x-app-context&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bwin_balance_query {
            get {
                return ResourceManager.GetString("bwin_balance_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fetch(&quot;[betslip_url]&quot;, {
        ///  &quot;headers&quot;: {
        ///    &quot;accept&quot;: &quot;application/json, text/plain, */*&quot;,
        ///    &quot;accept-language&quot;: &quot;en-US,en;q=0.9,ko;q=0.8&quot;,
        ///    &quot;cache-control&quot;: &quot;no-cache&quot;,
        ///    &quot;content-type&quot;: &quot;application/json&quot;,
        ///    &quot;pragma&quot;: &quot;no-cache&quot;,
        ///    &quot;priority&quot;: &quot;u=1, i&quot;,
        ///    &quot;sec-ch-ua&quot;: &quot;\&quot;Chromium\&quot;;v=\&quot;124\&quot;, \&quot;Google Chrome\&quot;;v=\&quot;124\&quot;, \&quot;Not-A.Brand\&quot;;v=\&quot;99\&quot;&quot;,
        ///    &quot;sec-ch-ua-mobile&quot;: &quot;?0&quot;,
        ///    &quot;sec-ch-ua-platform&quot;: &quot;\&quot;Windows\&quot;&quot;,
        ///    &quot;sec-fetch-dest&quot;: &quot;empty&quot;,
        ///    &quot;sec-fetch-mode&quot;: &quot;cors&quot;,
        ///    &quot;sec-fetch-s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bwin_betslip_query {
            get {
                return ResourceManager.GetString("bwin_betslip_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fetch(&quot;[balance_url]&quot;, {
        ///  &quot;headers&quot;: {
        ///    &quot;accept&quot;: &quot;application/json, text/plain, */*&quot;,
        ///    &quot;accept-language&quot;: &quot;en-US,en;q=0.9,ko;q=0.8&quot;,
        ///    &quot;cache-control&quot;: &quot;no-cache&quot;,
        ///    &quot;pragma&quot;: &quot;no-cache&quot;,
        ///    &quot;priority&quot;: &quot;u=1, i&quot;,
        ///    &quot;sec-ch-ua&quot;: &quot;\&quot;Chromium\&quot;;v=\&quot;124\&quot;, \&quot;Google Chrome\&quot;;v=\&quot;124\&quot;, \&quot;Not-A.Brand\&quot;;v=\&quot;99\&quot;&quot;,
        ///    &quot;sec-ch-ua-mobile&quot;: &quot;?0&quot;,
        ///    &quot;sec-ch-ua-platform&quot;: &quot;\&quot;Windows\&quot;&quot;,
        ///    &quot;sec-fetch-dest&quot;: &quot;empty&quot;,
        ///    &quot;sec-fetch-mode&quot;: &quot;cors&quot;,
        ///    &quot;sec-fetch-site&quot;: &quot;same-origin&quot;,
        ///    &quot;x-app-context&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bwin_placebet_query {
            get {
                return ResourceManager.GetString("bwin_placebet_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fetch(&quot;[balance_url]&quot;, {
        ///  &quot;headers&quot;: {
        ///    &quot;accept&quot;: &quot;application/json, text/plain, */*&quot;,
        ///    &quot;sec-ch-ua&quot;: &quot;\&quot;Google Chrome\&quot;;v=\&quot;125\&quot;, \&quot;Chromium\&quot;;v=\&quot;125\&quot;, \&quot;Not.A/Brand\&quot;;v=\&quot;24\&quot;&quot;,
        ///    &quot;sec-ch-ua-mobile&quot;: &quot;?0&quot;,
        ///    &quot;sec-ch-ua-platform&quot;: &quot;\&quot;Windows\&quot;&quot;
        ///  },
        ///  &quot;referrer&quot;: &quot;https://www.estrelabet.com/&quot;,
        ///  &quot;referrerPolicy&quot;: &quot;strict-origin-when-cross-origin&quot;,
        ///  &quot;body&quot;: null,
        ///  &quot;method&quot;: &quot;GET&quot;,
        ///  &quot;mode&quot;: &quot;cors&quot;,
        ///  &quot;credentials&quot;: &quot;omit&quot;
        ///}).then(response =&gt; response.json());.
        /// </summary>
        internal static string estralebet_balance_query {
            get {
                return ResourceManager.GetString("estralebet_balance_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fetch(&quot;[eventUrl]&quot;, {
        ///  &quot;headers&quot;: {
        ///    &quot;sec-ch-ua&quot;: &quot;\&quot;Google Chrome\&quot;;v=\&quot;125\&quot;, \&quot;Chromium\&quot;;v=\&quot;125\&quot;, \&quot;Not.A/Brand\&quot;;v=\&quot;24\&quot;&quot;,
        ///    &quot;sec-ch-ua-mobile&quot;: &quot;?0&quot;,
        ///    &quot;sec-ch-ua-platform&quot;: &quot;\&quot;Windows\&quot;&quot;
        ///  },
        ///  &quot;referrer&quot;: &quot;https://www.estrelabet.com/&quot;,
        ///  &quot;referrerPolicy&quot;: &quot;strict-origin-when-cross-origin&quot;,
        ///  &quot;body&quot;: null,
        ///  &quot;method&quot;: &quot;GET&quot;,
        ///  &quot;mode&quot;: &quot;cors&quot;,
        ///  &quot;credentials&quot;: &quot;omit&quot;
        ///}).then(response =&gt; response.json());.
        /// </summary>
        internal static string estralebet_eventfind_query {
            get {
                return ResourceManager.GetString("estralebet_eventfind_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fetch(&quot;[request_url]&quot;, {
        ///  &quot;headers&quot;: {
        ///    &quot;accept&quot;: &quot;*/*&quot;,
        ///    &quot;accept-language&quot;: &quot;en-US,en;q=0.9,ko;q=0.8&quot;,
        ///    &quot;cache-control&quot;: &quot;no-cache&quot;,
        ///    &quot;pragma&quot;: &quot;no-cache&quot;,
        ///    &quot;priority&quot;: &quot;u=1, i&quot;,
        ///    &quot;sec-ch-ua&quot;: &quot;\&quot;Chromium\&quot;;v=\&quot;124\&quot;, \&quot;Google Chrome\&quot;;v=\&quot;124\&quot;, \&quot;Not-A.Brand\&quot;;v=\&quot;99\&quot;&quot;,
        ///    &quot;sec-ch-ua-mobile&quot;: &quot;?0&quot;,
        ///    &quot;sec-ch-ua-platform&quot;: &quot;\&quot;Windows\&quot;&quot;,
        ///    &quot;sec-fetch-dest&quot;: &quot;empty&quot;,
        ///    &quot;sec-fetch-mode&quot;: &quot;cors&quot;,
        ///    &quot;sec-fetch-site&quot;: &quot;same-origin&quot;
        ///  },
        ///  &quot;referrer&quot;: &quot;https://www.kto.com/&quot;,
        ///  &quot;refe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string kto_event_query {
            get {
                return ResourceManager.GetString("kto_event_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;command&quot;:&quot;get&quot;,&quot;params&quot;:{&quot;source&quot;:&quot;betting&quot;,&quot;what&quot;:{&quot;game&quot;:[&quot;team1_name&quot;,&quot;team2_name&quot;,&quot;is_blocked&quot;,&quot;is_live&quot;,&quot;sport_alias&quot;,&quot;region_alias&quot;,&quot;express_min_len&quot;,&quot;_parent_id&quot;,&quot;start_ts&quot;,&quot;visible_in_prematch&quot;],&quot;market&quot;:[&quot;id&quot;,&quot;name&quot;,&quot;express_id&quot;,&quot;type&quot;,&quot;extra_info&quot;],&quot;event&quot;:[&quot;id&quot;,&quot;price&quot;,&quot;base&quot;,&quot;name&quot;,&quot;type_1&quot;,&quot;ew_allowed&quot;,&quot;sp_enabled&quot;]},&quot;where&quot;:{&quot;game&quot;:{&quot;id&quot;:[gameId]},&quot;market&quot;:{&quot;id&quot;:[marketId]},&quot;event&quot;:{&quot;id&quot;:[selectionId]}},&quot;subscribe&quot;:true},&quot;rid&quot;:&quot;08b0df00c1cab143a465736247629ae5746451da&quot;}.
        /// </summary>
        internal static string playpix_betslip_message {
            get {
                return ResourceManager.GetString("playpix_betslip_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;command&quot;:&quot;get&quot;,&quot;params&quot;:{&quot;source&quot;:&quot;betting&quot;,&quot;what&quot;:{&quot;sport&quot;:[&quot;name&quot;],&quot;region&quot;:[&quot;name&quot;],&quot;competition&quot;:[&quot;name&quot;],&quot;game&quot;:[&quot;id&quot;,&quot;stats&quot;,&quot;info&quot;,&quot;is_neutral_venue&quot;,&quot;add_info_name&quot;,&quot;text_info&quot;,&quot;markets_count&quot;,&quot;type&quot;,&quot;start_ts&quot;,&quot;is_stat_available&quot;,&quot;team1_id&quot;,&quot;team1_name&quot;,&quot;team2_id&quot;,&quot;team2_name&quot;,&quot;last_event&quot;,&quot;live_events&quot;,&quot;match_length&quot;,&quot;sport_alias&quot;,&quot;sportcast_id&quot;,&quot;region_alias&quot;,&quot;is_blocked&quot;,&quot;show_type&quot;,&quot;game_number&quot;],&quot;market&quot;:[&quot;id&quot;,&quot;group_id&quot;,&quot;group_name&quot;,&quot;group_order&quot;,&quot;type&quot;,&quot;name_template&quot;,&quot;sequence&quot;,&quot;point_seq [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string playpix_event_message {
            get {
                return ResourceManager.GetString("playpix_event_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;command&quot;:&quot;get_max_bet&quot;,&quot;params&quot;:{&quot;events&quot;:[[selId]],&quot;type&quot;:1},&quot;rid&quot;:&quot;a02d3882a48db6158ca3d1044fe95ff69238f661&quot;}.
        /// </summary>
        internal static string playpix_getmax_message {
            get {
                return ResourceManager.GetString("playpix_getmax_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;command&quot;:&quot;create_bets&quot;,&quot;params&quot;:{&quot;bets&quot;:[{&quot;Source&quot;:42,&quot;Type&quot;:1,&quot;AcceptTypeId&quot;:2,&quot;OddType&quot;:0,&quot;EachWay&quot;:false,&quot;Events&quot;:[{&quot;SelectionId&quot;:[selId],&quot;Coeficient&quot;:[odds]}],&quot;IsSuperBet&quot;:false,&quot;Amount&quot;:[stake]}]},&quot;rid&quot;:&quot;8493ba482943f7cf4ed107202cfc05aa51a9482b&quot;}.
        /// </summary>
        internal static string playpix_placebet_message {
            get {
                return ResourceManager.GetString("playpix_placebet_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;command&quot;:&quot;get&quot;,&quot;params&quot;:{&quot;source&quot;:&quot;betting&quot;,&quot;what&quot;:{&quot;sport&quot;:[&quot;id&quot;,&quot;name&quot;,&quot;alias&quot;,&quot;order&quot;],&quot;competition&quot;:[&quot;id&quot;,&quot;order&quot;,&quot;name&quot;],&quot;region&quot;:[&quot;id&quot;,&quot;name&quot;,&quot;alias&quot;,&quot;order&quot;],&quot;game&quot;:&quot;@count&quot;},&quot;where&quot;:{&quot;game&quot;:{&quot;@or&quot;:[{&quot;visible_in_prematch&quot;:1},{&quot;type&quot;:{&quot;@in&quot;:[0,2]}}]},&quot;sport&quot;:{&quot;type&quot;:{&quot;@nin&quot;:[1,4]}}},&quot;subscribe&quot;:true},&quot;rid&quot;:&quot;c9bee840a414e09380d3051903eac49048252bfb&quot;}.
        /// </summary>
        internal static string playpix_sport_message {
            get {
                return ResourceManager.GetString("playpix_sport_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fetch(&quot;[balance_url]&quot;, {
        ///  &quot;headers&quot;: {
        ///    &quot;accept&quot;: &quot;text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7&quot;,
        ///    &quot;accept-language&quot;: &quot;en-US,en;q=0.9,ko;q=0.8&quot;,
        ///    &quot;cache-control&quot;: &quot;no-cache&quot;,
        ///    &quot;pragma&quot;: &quot;no-cache&quot;,
        ///    &quot;priority&quot;: &quot;u=0, i&quot;,
        ///    &quot;sec-ch-ua&quot;: &quot;\&quot;Not)A;Brand\&quot;;v=\&quot;99\&quot;, \&quot;Google Chrome\&quot;;v=\&quot;127\&quot;, \&quot;Chromium\&quot;;v=\&quot;127\&quot;&quot;,
        ///    &quot;sec-ch-ua-mobile&quot;: &quot;?0&quot;,
        ///    &quot;sec-ch-ua-platform&quot;: &quot;\&quot;Windows\&quot;&quot;,
        ///    &quot;sec-fetch- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string winamax_balance_query {
            get {
                return ResourceManager.GetString("winamax_balance_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fetch(&quot;https://www.winamax.es/betting/validate_betslip.php&quot;, {
        ///  &quot;headers&quot;: {
        ///    &quot;accept&quot;: &quot;*/*&quot;,
        ///    &quot;accept-language&quot;: &quot;en-US,en;q=0.9,ko;q=0.8&quot;,
        ///    &quot;cache-control&quot;: &quot;no-cache&quot;,
        ///    &quot;content-type&quot;: &quot;application/x-www-form-urlencoded&quot;,
        ///    &quot;pragma&quot;: &quot;no-cache&quot;,
        ///    &quot;priority&quot;: &quot;u=1, i&quot;,
        ///    &quot;sec-ch-ua&quot;: &quot;\&quot;Not)A;Brand\&quot;;v=\&quot;99\&quot;, \&quot;Google Chrome\&quot;;v=\&quot;127\&quot;, \&quot;Chromium\&quot;;v=\&quot;127\&quot;&quot;,
        ///    &quot;sec-ch-ua-mobile&quot;: &quot;?0&quot;,
        ///    &quot;sec-ch-ua-platform&quot;: &quot;\&quot;Windows\&quot;&quot;,
        ///    &quot;sec-fetch-dest&quot;: &quot;empty&quot;,
        ///    &quot;sec-fetch-mode&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string winamax_placebet_query {
            get {
                return ResourceManager.GetString("winamax_placebet_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpandMarkets();
        ///  function  ExpandMarkets(){
        ///    var elements = document.getElementsByClassName(&apos;expand-button&apos;);
        ///    for (let i = 0; i &lt; elements.length ; i++) {
        ///        try{
        ///            elements[i].click();
        ///        }
        ///        catch(ex){
        ///
        ///        }
        ///    }
        ///  }.
        /// </summary>
        internal static string winamax_scrip2 {
            get {
                return ResourceManager.GetString("winamax_scrip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnableTabs();
        ///  function  EnableTabs(){
        ///    var elements = document.getElementsByClassName(&apos;tabs-wrapper&apos;);
        ///    for (let i = 0; i &lt; elements.length ; i++) {
        ///        try{
        ///            elements[i].getElementsByTagName(&apos;div&apos;)[0].click();
        ///        }
        ///        catch(ex){
        ///
        ///        }
        ///    }
        ///  }.
        /// </summary>
        internal static string winamax_script1 {
            get {
                return ResourceManager.GetString("winamax_script1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fetch(&quot;https://apuestas.wplay.co/web_nr&quot;, {
        ///  &quot;headers&quot;: {
        ///    &quot;accept&quot;: &quot;application/json, text/javascript, */*; q=0.01&quot;,
        ///    &quot;accept-language&quot;: &quot;en-US,en;q=0.9&quot;,
        ///    &quot;content-type&quot;: &quot;application/x-www-form-urlencoded; charset=UTF-8&quot;,
        ///    &quot;priority&quot;: &quot;u=1, i&quot;,
        ///    &quot;sec-ch-ua&quot;: &quot;\&quot;Chromium\&quot;;v=\&quot;130\&quot;, \&quot;Google Chrome\&quot;;v=\&quot;130\&quot;, \&quot;Not?A_Brand\&quot;;v=\&quot;99\&quot;&quot;,
        ///    &quot;sec-ch-ua-mobile&quot;: &quot;?0&quot;,
        ///    &quot;sec-ch-ua-platform&quot;: &quot;\&quot;Windows\&quot;&quot;,
        ///    &quot;sec-fetch-dest&quot;: &quot;empty&quot;,
        ///    &quot;sec-fetch-mode&quot;: &quot;cors&quot;,
        ///    &quot;sec-fetch-site&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wplay_addbet_query {
            get {
                return ResourceManager.GetString("wplay_addbet_query", resourceCulture);
            }
        }
    }
}
